package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Escala generated by hbm2java
 */
public class Escala implements java.io.Serializable {

	private String codigoEscala;
	private String nombre;
	private short porcentajeInicial;
	private short porcentajeFinal;
	private Byte ordenPresentacion;
	private Set evaluacionPatronPrincipiosForPrConceptualizadoEscala = new HashSet(
			0);
	private Set evaluacionPatronsForPtConceptualizadoEscala = new HashSet(0);
	private Set evaluacionPatronPrincipiosForPrImplementadoEscala = new HashSet(
			0);
	private Set evaluacionPatronPrincipiosForPrAdoptadoEscala = new HashSet(0);
	private Set evaluacionPatronPrincipiosForPrDocumentadoEscala = new HashSet(
			0);
	private Set evaluacionPatronsForPtAdoptadoEscala = new HashSet(0);
	private Set evaluacionPatronPrincipiosForPrPublicadoEscala = new HashSet(0);
	private Set evaluacionPatronsForPtPublicadoEscala = new HashSet(0);
	private Set evaluacionPatronsForPtDocumentadoEscala = new HashSet(0);
	private Set evaluacionPatronsForPtImplementadoEscala = new HashSet(0);

	public Escala() {
	}

	public Escala(String codigoEscala, String nombre, short porcentajeInicial,
			short porcentajeFinal) {
		this.codigoEscala = codigoEscala;
		this.nombre = nombre;
		this.porcentajeInicial = porcentajeInicial;
		this.porcentajeFinal = porcentajeFinal;
	}

	public Escala(String codigoEscala, String nombre, short porcentajeInicial,
			short porcentajeFinal, Byte ordenPresentacion,
			Set evaluacionPatronPrincipiosForPrConceptualizadoEscala,
			Set evaluacionPatronsForPtConceptualizadoEscala,
			Set evaluacionPatronPrincipiosForPrImplementadoEscala,
			Set evaluacionPatronPrincipiosForPrAdoptadoEscala,
			Set evaluacionPatronPrincipiosForPrDocumentadoEscala,
			Set evaluacionPatronsForPtAdoptadoEscala,
			Set evaluacionPatronPrincipiosForPrPublicadoEscala,
			Set evaluacionPatronsForPtPublicadoEscala,
			Set evaluacionPatronsForPtDocumentadoEscala,
			Set evaluacionPatronsForPtImplementadoEscala) {
		this.codigoEscala = codigoEscala;
		this.nombre = nombre;
		this.porcentajeInicial = porcentajeInicial;
		this.porcentajeFinal = porcentajeFinal;
		this.ordenPresentacion = ordenPresentacion;
		this.evaluacionPatronPrincipiosForPrConceptualizadoEscala = evaluacionPatronPrincipiosForPrConceptualizadoEscala;
		this.evaluacionPatronsForPtConceptualizadoEscala = evaluacionPatronsForPtConceptualizadoEscala;
		this.evaluacionPatronPrincipiosForPrImplementadoEscala = evaluacionPatronPrincipiosForPrImplementadoEscala;
		this.evaluacionPatronPrincipiosForPrAdoptadoEscala = evaluacionPatronPrincipiosForPrAdoptadoEscala;
		this.evaluacionPatronPrincipiosForPrDocumentadoEscala = evaluacionPatronPrincipiosForPrDocumentadoEscala;
		this.evaluacionPatronsForPtAdoptadoEscala = evaluacionPatronsForPtAdoptadoEscala;
		this.evaluacionPatronPrincipiosForPrPublicadoEscala = evaluacionPatronPrincipiosForPrPublicadoEscala;
		this.evaluacionPatronsForPtPublicadoEscala = evaluacionPatronsForPtPublicadoEscala;
		this.evaluacionPatronsForPtDocumentadoEscala = evaluacionPatronsForPtDocumentadoEscala;
		this.evaluacionPatronsForPtImplementadoEscala = evaluacionPatronsForPtImplementadoEscala;
	}

	public String getCodigoEscala() {
		return this.codigoEscala;
	}

	public void setCodigoEscala(String codigoEscala) {
		this.codigoEscala = codigoEscala;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public short getPorcentajeInicial() {
		return this.porcentajeInicial;
	}

	public void setPorcentajeInicial(short porcentajeInicial) {
		this.porcentajeInicial = porcentajeInicial;
	}

	public short getPorcentajeFinal() {
		return this.porcentajeFinal;
	}

	public void setPorcentajeFinal(short porcentajeFinal) {
		this.porcentajeFinal = porcentajeFinal;
	}

	public Byte getOrdenPresentacion() {
		return this.ordenPresentacion;
	}

	public void setOrdenPresentacion(Byte ordenPresentacion) {
		this.ordenPresentacion = ordenPresentacion;
	}

	public Set getEvaluacionPatronPrincipiosForPrConceptualizadoEscala() {
		return this.evaluacionPatronPrincipiosForPrConceptualizadoEscala;
	}

	public void setEvaluacionPatronPrincipiosForPrConceptualizadoEscala(
			Set evaluacionPatronPrincipiosForPrConceptualizadoEscala) {
		this.evaluacionPatronPrincipiosForPrConceptualizadoEscala = evaluacionPatronPrincipiosForPrConceptualizadoEscala;
	}

	public Set getEvaluacionPatronsForPtConceptualizadoEscala() {
		return this.evaluacionPatronsForPtConceptualizadoEscala;
	}

	public void setEvaluacionPatronsForPtConceptualizadoEscala(
			Set evaluacionPatronsForPtConceptualizadoEscala) {
		this.evaluacionPatronsForPtConceptualizadoEscala = evaluacionPatronsForPtConceptualizadoEscala;
	}

	public Set getEvaluacionPatronPrincipiosForPrImplementadoEscala() {
		return this.evaluacionPatronPrincipiosForPrImplementadoEscala;
	}

	public void setEvaluacionPatronPrincipiosForPrImplementadoEscala(
			Set evaluacionPatronPrincipiosForPrImplementadoEscala) {
		this.evaluacionPatronPrincipiosForPrImplementadoEscala = evaluacionPatronPrincipiosForPrImplementadoEscala;
	}

	public Set getEvaluacionPatronPrincipiosForPrAdoptadoEscala() {
		return this.evaluacionPatronPrincipiosForPrAdoptadoEscala;
	}

	public void setEvaluacionPatronPrincipiosForPrAdoptadoEscala(
			Set evaluacionPatronPrincipiosForPrAdoptadoEscala) {
		this.evaluacionPatronPrincipiosForPrAdoptadoEscala = evaluacionPatronPrincipiosForPrAdoptadoEscala;
	}

	public Set getEvaluacionPatronPrincipiosForPrDocumentadoEscala() {
		return this.evaluacionPatronPrincipiosForPrDocumentadoEscala;
	}

	public void setEvaluacionPatronPrincipiosForPrDocumentadoEscala(
			Set evaluacionPatronPrincipiosForPrDocumentadoEscala) {
		this.evaluacionPatronPrincipiosForPrDocumentadoEscala = evaluacionPatronPrincipiosForPrDocumentadoEscala;
	}

	public Set getEvaluacionPatronsForPtAdoptadoEscala() {
		return this.evaluacionPatronsForPtAdoptadoEscala;
	}

	public void setEvaluacionPatronsForPtAdoptadoEscala(
			Set evaluacionPatronsForPtAdoptadoEscala) {
		this.evaluacionPatronsForPtAdoptadoEscala = evaluacionPatronsForPtAdoptadoEscala;
	}

	public Set getEvaluacionPatronPrincipiosForPrPublicadoEscala() {
		return this.evaluacionPatronPrincipiosForPrPublicadoEscala;
	}

	public void setEvaluacionPatronPrincipiosForPrPublicadoEscala(
			Set evaluacionPatronPrincipiosForPrPublicadoEscala) {
		this.evaluacionPatronPrincipiosForPrPublicadoEscala = evaluacionPatronPrincipiosForPrPublicadoEscala;
	}

	public Set getEvaluacionPatronsForPtPublicadoEscala() {
		return this.evaluacionPatronsForPtPublicadoEscala;
	}

	public void setEvaluacionPatronsForPtPublicadoEscala(
			Set evaluacionPatronsForPtPublicadoEscala) {
		this.evaluacionPatronsForPtPublicadoEscala = evaluacionPatronsForPtPublicadoEscala;
	}

	public Set getEvaluacionPatronsForPtDocumentadoEscala() {
		return this.evaluacionPatronsForPtDocumentadoEscala;
	}

	public void setEvaluacionPatronsForPtDocumentadoEscala(
			Set evaluacionPatronsForPtDocumentadoEscala) {
		this.evaluacionPatronsForPtDocumentadoEscala = evaluacionPatronsForPtDocumentadoEscala;
	}

	public Set getEvaluacionPatronsForPtImplementadoEscala() {
		return this.evaluacionPatronsForPtImplementadoEscala;
	}

	public void setEvaluacionPatronsForPtImplementadoEscala(
			Set evaluacionPatronsForPtImplementadoEscala) {
		this.evaluacionPatronsForPtImplementadoEscala = evaluacionPatronsForPtImplementadoEscala;
	}

}
