package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * Estado generated by hbm2java
 */
public class Estado implements java.io.Serializable {

	private String codigoEstado;
	private String nombre;
	private String implementa;
	private boolean estadoInicial;
	private boolean estadoFinal;
	private String siguienteEstado;

	public Estado() {
	}

	public Estado(String codigoEstado, String nombre, String implementa,
			boolean estadoInicial, boolean estadoFinal) {
		this.codigoEstado = codigoEstado;
		this.nombre = nombre;
		this.implementa = implementa;
		this.estadoInicial = estadoInicial;
		this.estadoFinal = estadoFinal;
	}

	public Estado(String codigoEstado, String nombre, String implementa,
			boolean estadoInicial, boolean estadoFinal, String siguienteEstado) {
		this.codigoEstado = codigoEstado;
		this.nombre = nombre;
		this.implementa = implementa;
		this.estadoInicial = estadoInicial;
		this.estadoFinal = estadoFinal;
		this.siguienteEstado = siguienteEstado;
	}

	public String getCodigoEstado() {
		return this.codigoEstado;
	}

	public void setCodigoEstado(String codigoEstado) {
		this.codigoEstado = codigoEstado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getImplementa() {
		return this.implementa;
	}

	public void setImplementa(String implementa) {
		this.implementa = implementa;
	}

	public boolean isEstadoInicial() {
		return this.estadoInicial;
	}

	public void setEstadoInicial(boolean estadoInicial) {
		this.estadoInicial = estadoInicial;
	}

	public boolean isEstadoFinal() {
		return this.estadoFinal;
	}

	public void setEstadoFinal(boolean estadoFinal) {
		this.estadoFinal = estadoFinal;
	}

	public String getSiguienteEstado() {
		return this.siguienteEstado;
	}

	public void setSiguienteEstado(String siguienteEstado) {
		this.siguienteEstado = siguienteEstado;
	}

}
