package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EvaluacionPatronPrincipio generated by hbm2java
 */
public class EvaluacionPatronPrincipio implements java.io.Serializable {

	private EvaluacionPatronPrincipioId id;
	private Escala escalaByPrPublicadoEscala;
	private Escala escalaByPrDocumentadoEscala;
	private Escala escalaByPrImplementadoEscala;
	private Escala escalaByPrAdoptadoEscala;
	private EvaluacionPatron evaluacionPatron;
	private Principio principio;
	private Escala escalaByPrConceptualizadoEscala;
	private Short prConceptualizadoPrecision;
	private Short prDocumentadoPrecision;
	private Short prPublicadoPrecision;
	private Short prAdoptadoPrecision;
	private Short prImplementadoPrecision;
	private String apreciacion;
	private Date fechaActualizacion;

	public EvaluacionPatronPrincipio() {
	}

	public EvaluacionPatronPrincipio(EvaluacionPatronPrincipioId id,
			Escala escalaByPrPublicadoEscala,
			Escala escalaByPrDocumentadoEscala,
			Escala escalaByPrImplementadoEscala,
			Escala escalaByPrAdoptadoEscala, EvaluacionPatron evaluacionPatron,
			Principio principio, Escala escalaByPrConceptualizadoEscala,
			Date fechaActualizacion) {
		this.id = id;
		this.escalaByPrPublicadoEscala = escalaByPrPublicadoEscala;
		this.escalaByPrDocumentadoEscala = escalaByPrDocumentadoEscala;
		this.escalaByPrImplementadoEscala = escalaByPrImplementadoEscala;
		this.escalaByPrAdoptadoEscala = escalaByPrAdoptadoEscala;
		this.evaluacionPatron = evaluacionPatron;
		this.principio = principio;
		this.escalaByPrConceptualizadoEscala = escalaByPrConceptualizadoEscala;
		this.fechaActualizacion = fechaActualizacion;
	}

	public EvaluacionPatronPrincipio(EvaluacionPatronPrincipioId id,
			Escala escalaByPrPublicadoEscala,
			Escala escalaByPrDocumentadoEscala,
			Escala escalaByPrImplementadoEscala,
			Escala escalaByPrAdoptadoEscala, EvaluacionPatron evaluacionPatron,
			Principio principio, Escala escalaByPrConceptualizadoEscala,
			Short prConceptualizadoPrecision, Short prDocumentadoPrecision,
			Short prPublicadoPrecision, Short prAdoptadoPrecision,
			Short prImplementadoPrecision, String apreciacion,
			Date fechaActualizacion) {
		this.id = id;
		this.escalaByPrPublicadoEscala = escalaByPrPublicadoEscala;
		this.escalaByPrDocumentadoEscala = escalaByPrDocumentadoEscala;
		this.escalaByPrImplementadoEscala = escalaByPrImplementadoEscala;
		this.escalaByPrAdoptadoEscala = escalaByPrAdoptadoEscala;
		this.evaluacionPatron = evaluacionPatron;
		this.principio = principio;
		this.escalaByPrConceptualizadoEscala = escalaByPrConceptualizadoEscala;
		this.prConceptualizadoPrecision = prConceptualizadoPrecision;
		this.prDocumentadoPrecision = prDocumentadoPrecision;
		this.prPublicadoPrecision = prPublicadoPrecision;
		this.prAdoptadoPrecision = prAdoptadoPrecision;
		this.prImplementadoPrecision = prImplementadoPrecision;
		this.apreciacion = apreciacion;
		this.fechaActualizacion = fechaActualizacion;
	}

	public EvaluacionPatronPrincipioId getId() {
		return this.id;
	}

	public void setId(EvaluacionPatronPrincipioId id) {
		this.id = id;
	}

	public Escala getEscalaByPrPublicadoEscala() {
		return this.escalaByPrPublicadoEscala;
	}

	public void setEscalaByPrPublicadoEscala(Escala escalaByPrPublicadoEscala) {
		this.escalaByPrPublicadoEscala = escalaByPrPublicadoEscala;
	}

	public Escala getEscalaByPrDocumentadoEscala() {
		return this.escalaByPrDocumentadoEscala;
	}

	public void setEscalaByPrDocumentadoEscala(
			Escala escalaByPrDocumentadoEscala) {
		this.escalaByPrDocumentadoEscala = escalaByPrDocumentadoEscala;
	}

	public Escala getEscalaByPrImplementadoEscala() {
		return this.escalaByPrImplementadoEscala;
	}

	public void setEscalaByPrImplementadoEscala(
			Escala escalaByPrImplementadoEscala) {
		this.escalaByPrImplementadoEscala = escalaByPrImplementadoEscala;
	}

	public Escala getEscalaByPrAdoptadoEscala() {
		return this.escalaByPrAdoptadoEscala;
	}

	public void setEscalaByPrAdoptadoEscala(Escala escalaByPrAdoptadoEscala) {
		this.escalaByPrAdoptadoEscala = escalaByPrAdoptadoEscala;
	}

	public EvaluacionPatron getEvaluacionPatron() {
		return this.evaluacionPatron;
	}

	public void setEvaluacionPatron(EvaluacionPatron evaluacionPatron) {
		this.evaluacionPatron = evaluacionPatron;
	}

	public Principio getPrincipio() {
		return this.principio;
	}

	public void setPrincipio(Principio principio) {
		this.principio = principio;
	}

	public Escala getEscalaByPrConceptualizadoEscala() {
		return this.escalaByPrConceptualizadoEscala;
	}

	public void setEscalaByPrConceptualizadoEscala(
			Escala escalaByPrConceptualizadoEscala) {
		this.escalaByPrConceptualizadoEscala = escalaByPrConceptualizadoEscala;
	}

	public Short getPrConceptualizadoPrecision() {
		return this.prConceptualizadoPrecision;
	}

	public void setPrConceptualizadoPrecision(Short prConceptualizadoPrecision) {
		this.prConceptualizadoPrecision = prConceptualizadoPrecision;
	}

	public Short getPrDocumentadoPrecision() {
		return this.prDocumentadoPrecision;
	}

	public void setPrDocumentadoPrecision(Short prDocumentadoPrecision) {
		this.prDocumentadoPrecision = prDocumentadoPrecision;
	}

	public Short getPrPublicadoPrecision() {
		return this.prPublicadoPrecision;
	}

	public void setPrPublicadoPrecision(Short prPublicadoPrecision) {
		this.prPublicadoPrecision = prPublicadoPrecision;
	}

	public Short getPrAdoptadoPrecision() {
		return this.prAdoptadoPrecision;
	}

	public void setPrAdoptadoPrecision(Short prAdoptadoPrecision) {
		this.prAdoptadoPrecision = prAdoptadoPrecision;
	}

	public Short getPrImplementadoPrecision() {
		return this.prImplementadoPrecision;
	}

	public void setPrImplementadoPrecision(Short prImplementadoPrecision) {
		this.prImplementadoPrecision = prImplementadoPrecision;
	}

	public String getApreciacion() {
		return this.apreciacion;
	}

	public void setApreciacion(String apreciacion) {
		this.apreciacion = apreciacion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
