package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ImplementacionCategoria generated by hbm2java
 */
public class ImplementacionCategoria implements java.io.Serializable {

	private ImplementacionCategoriaId id;
	private Categoria categoria;
	private Implementacion implementacion;
	private Date fechaRegistro;

	public ImplementacionCategoria() {
	}

	public ImplementacionCategoria(ImplementacionCategoriaId id,
			Categoria categoria, Implementacion implementacion) {
		this.id = id;
		this.categoria = categoria;
		this.implementacion = implementacion;
	}

	public ImplementacionCategoria(ImplementacionCategoriaId id,
			Categoria categoria, Implementacion implementacion,
			Date fechaRegistro) {
		this.id = id;
		this.categoria = categoria;
		this.implementacion = implementacion;
		this.fechaRegistro = fechaRegistro;
	}

	public ImplementacionCategoriaId getId() {
		return this.id;
	}

	public void setId(ImplementacionCategoriaId id) {
		this.id = id;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Implementacion getImplementacion() {
		return this.implementacion;
	}

	public void setImplementacion(Implementacion implementacion) {
		this.implementacion = implementacion;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

}
