package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Patron generated by hbm2java
 */
public class Patron implements java.io.Serializable {

	private String codigoPatron;
	private Categoria categoria;
	private String nombre;
	private String url;
	private String problema;
	private String solucion;
	private String aplicacion;
	private String impacto;
	private Set evaluacionPatrons = new HashSet(0);
	private Set principios = new HashSet(0);

	public Patron() {
	}

	public Patron(String codigoPatron, Categoria categoria, String nombre) {
		this.codigoPatron = codigoPatron;
		this.categoria = categoria;
		this.nombre = nombre;
	}

	public Patron(String codigoPatron, Categoria categoria, String nombre,
			String url, String problema, String solucion, String aplicacion,
			String impacto, Set evaluacionPatrons, Set principios) {
		this.codigoPatron = codigoPatron;
		this.categoria = categoria;
		this.nombre = nombre;
		this.url = url;
		this.problema = problema;
		this.solucion = solucion;
		this.aplicacion = aplicacion;
		this.impacto = impacto;
		this.evaluacionPatrons = evaluacionPatrons;
		this.principios = principios;
	}

	public String getCodigoPatron() {
		return this.codigoPatron;
	}

	public void setCodigoPatron(String codigoPatron) {
		this.codigoPatron = codigoPatron;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getProblema() {
		return this.problema;
	}

	public void setProblema(String problema) {
		this.problema = problema;
	}

	public String getSolucion() {
		return this.solucion;
	}

	public void setSolucion(String solucion) {
		this.solucion = solucion;
	}

	public String getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(String aplicacion) {
		this.aplicacion = aplicacion;
	}

	public String getImpacto() {
		return this.impacto;
	}

	public void setImpacto(String impacto) {
		this.impacto = impacto;
	}

	public Set getEvaluacionPatrons() {
		return this.evaluacionPatrons;
	}

	public void setEvaluacionPatrons(Set evaluacionPatrons) {
		this.evaluacionPatrons = evaluacionPatrons;
	}

	public Set getPrincipios() {
		return this.principios;
	}

	public void setPrincipios(Set principios) {
		this.principios = principios;
	}

}
