package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProyectoPersona generated by hbm2java
 */
public class ProyectoPersona implements java.io.Serializable {

	private ProyectoPersonaId id;
	private Persona persona;
	private Proyecto proyecto;
	private Rol rol;

	public ProyectoPersona() {
	}

	public ProyectoPersona(ProyectoPersonaId id, Persona persona,
			Proyecto proyecto, Rol rol) {
		this.id = id;
		this.persona = persona;
		this.proyecto = proyecto;
		this.rol = rol;
	}

	public ProyectoPersonaId getId() {
		return this.id;
	}

	public void setId(ProyectoPersonaId id) {
		this.id = id;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
