package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private long codigoProyecto;
	private Persona persona;
	private Date fechaRegistro;
	private Date fechaModificacion;
	private String estado;
	private String nombre;
	private String organizacion;
	private String url;
	private String observacion;
	private String pais;
	private Set implementacions = new HashSet(0);
	private Set proyectoPersonas = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(long codigoProyecto, Persona persona, Date fechaRegistro,
			Date fechaModificacion, String estado, String nombre) {
		this.codigoProyecto = codigoProyecto;
		this.persona = persona;
		this.fechaRegistro = fechaRegistro;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.nombre = nombre;
	}

	public Proyecto(long codigoProyecto, Persona persona, Date fechaRegistro,
			Date fechaModificacion, String estado, String nombre,
			String organizacion, String url, String observacion, String pais,
			Set implementacions, Set proyectoPersonas) {
		this.codigoProyecto = codigoProyecto;
		this.persona = persona;
		this.fechaRegistro = fechaRegistro;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.nombre = nombre;
		this.organizacion = organizacion;
		this.url = url;
		this.observacion = observacion;
		this.pais = pais;
		this.implementacions = implementacions;
		this.proyectoPersonas = proyectoPersonas;
	}

	public long getCodigoProyecto() {
		return this.codigoProyecto;
	}

	public void setCodigoProyecto(long codigoProyecto) {
		this.codigoProyecto = codigoProyecto;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getOrganizacion() {
		return this.organizacion;
	}

	public void setOrganizacion(String organizacion) {
		this.organizacion = organizacion;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set getImplementacions() {
		return this.implementacions;
	}

	public void setImplementacions(Set implementacions) {
		this.implementacions = implementacions;
	}

	public Set getProyectoPersonas() {
		return this.proyectoPersonas;
	}

	public void setProyectoPersonas(Set proyectoPersonas) {
		this.proyectoPersonas = proyectoPersonas;
	}

}
