package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private String codigoRol;
	private String nombre;
	private Set proyectoPersonas = new HashSet(0);

	public Rol() {
	}

	public Rol(String codigoRol) {
		this.codigoRol = codigoRol;
	}
	
	public Rol(String codigoRol, String nombre) {
		this.codigoRol = codigoRol;
		this.nombre = nombre;
	}

	public Rol(String codigoRol, String nombre, Set proyectoPersonas) {
		this.codigoRol = codigoRol;
		this.nombre = nombre;
		this.proyectoPersonas = proyectoPersonas;
	}

	public String getCodigoRol() {
		return this.codigoRol;
	}

	public void setCodigoRol(String codigoRol) {
		this.codigoRol = codigoRol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProyectoPersonas() {
		return this.proyectoPersonas;
	}

	public void setProyectoPersonas(Set proyectoPersonas) {
		this.proyectoPersonas = proyectoPersonas;
	}

}
