package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion implements java.io.Serializable {

	private Long codigoEvaluacion;
	private Persona persona;
	private Implementacion implementacion;
	private String apreciacion;
	private String estado;
	private Date fechaActualizacion;
	private Set evaluacionPatrons = new HashSet(0);

	public Evaluacion() {
	}

	public Evaluacion(Long codigoEvaluacion, Persona persona,
			Implementacion implementacion, String estado,
			Date fechaActualizacion) {
		this.codigoEvaluacion = codigoEvaluacion;
		this.persona = persona;
		this.implementacion = implementacion;
		this.estado = estado;
		this.fechaActualizacion = fechaActualizacion;
	}

	public Evaluacion(Long codigoEvaluacion, Persona persona,
			Implementacion implementacion, String apreciacion, String estado,
			Date fechaActualizacion, Set evaluacionPatrons) {
		this.codigoEvaluacion = codigoEvaluacion;
		this.persona = persona;
		this.implementacion = implementacion;
		this.apreciacion = apreciacion;
		this.estado = estado;
		this.fechaActualizacion = fechaActualizacion;
		this.evaluacionPatrons = evaluacionPatrons;
	}

	public Long getCodigoEvaluacion() {
		return this.codigoEvaluacion;
	}

	public void setCodigoEvaluacion(Long codigoEvaluacion) {
		this.codigoEvaluacion = codigoEvaluacion;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Implementacion getImplementacion() {
		return this.implementacion;
	}

	public void setImplementacion(Implementacion implementacion) {
		this.implementacion = implementacion;
	}

	public String getApreciacion() {
		return this.apreciacion;
	}

	public void setApreciacion(String apreciacion) {
		this.apreciacion = apreciacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Set getEvaluacionPatrons() {
		return this.evaluacionPatrons;
	}

	public void setEvaluacionPatrons(Set evaluacionPatrons) {
		this.evaluacionPatrons = evaluacionPatrons;
	}

}
