package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * ImplementacionCategoriaId generated by hbm2java
 */
public class ImplementacionCategoriaId implements java.io.Serializable {

	private String codigoCategoria;
	private long codigoImplementacion;

	public ImplementacionCategoriaId() {
	}

	public ImplementacionCategoriaId(String codigoCategoria,
			long codigoImplementacion) {
		this.codigoCategoria = codigoCategoria;
		this.codigoImplementacion = codigoImplementacion;
	}

	public String getCodigoCategoria() {
		return this.codigoCategoria;
	}

	public void setCodigoCategoria(String codigoCategoria) {
		this.codigoCategoria = codigoCategoria;
	}

	public long getCodigoImplementacion() {
		return this.codigoImplementacion;
	}

	public void setCodigoImplementacion(long codigoImplementacion) {
		this.codigoImplementacion = codigoImplementacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImplementacionCategoriaId))
			return false;
		ImplementacionCategoriaId castOther = (ImplementacionCategoriaId) other;

		return ((this.getCodigoCategoria() == castOther.getCodigoCategoria()) || (this
				.getCodigoCategoria() != null
				&& castOther.getCodigoCategoria() != null && this
				.getCodigoCategoria().equals(castOther.getCodigoCategoria())))
				&& (this.getCodigoImplementacion() == castOther
						.getCodigoImplementacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoCategoria() == null ? 0 : this.getCodigoCategoria()
						.hashCode());
		result = 37 * result + (int) this.getCodigoImplementacion();
		return result;
	}

}
