package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Implementacion generated by hbm2java
 */
public class Implementacion implements java.io.Serializable {

	private Long codigoImplementacion;
	private Proyecto proyecto;
	private Date fechaRegistro;
	private Date fechaModificacion;
	private String estado;
	private String nombre;
	private String observacion;
	private Set evaluacions = new HashSet(0);
	private Set<ImplementacionCategoria> implementacionCategorias = new HashSet<ImplementacionCategoria>(0);
	private List<ImplementacionCategoria> listImplementacionCategorias=new ArrayList<ImplementacionCategoria>();

	public Implementacion() {
	}

	public Implementacion(Long codigoImplementacion, Proyecto proyecto,
			Date fechaRegistro, Date fechaModificacion, String estado,
			String nombre) {
		this.codigoImplementacion = codigoImplementacion;
		this.proyecto = proyecto;
		this.fechaRegistro = fechaRegistro;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.nombre = nombre;
	}

	public Implementacion(Long codigoImplementacion, Proyecto proyecto,
			Date fechaRegistro, Date fechaModificacion, String estado,
			String nombre, String observacion, Set evaluacions,
			Set implementacionCategorias) {
		this.codigoImplementacion = codigoImplementacion;
		this.proyecto = proyecto;
		this.fechaRegistro = fechaRegistro;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.nombre = nombre;
		this.observacion = observacion;
		this.evaluacions = evaluacions;
		this.implementacionCategorias = implementacionCategorias;
	}

	public Long getCodigoImplementacion() {
		return this.codigoImplementacion;
	}

	public void setCodigoImplementacion(Long codigoImplementacion) {
		this.codigoImplementacion = codigoImplementacion;
	}

	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Set getEvaluacions() {
		return this.evaluacions;
	}

	public void setEvaluacions(Set evaluacions) {
		this.evaluacions = evaluacions;
	}

	public Set<ImplementacionCategoria> getImplementacionCategorias() {
		return this.implementacionCategorias;
	}

	public void setImplementacionCategorias(Set<ImplementacionCategoria> implementacionCategorias) {
		this.implementacionCategorias = implementacionCategorias;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 30/07/2013
	 * @return the listImplementacionCategorias
	 */
	public List<ImplementacionCategoria> getListImplementacionCategorias() {
		if(implementacionCategorias.size()>0){
			listImplementacionCategorias=new ArrayList<ImplementacionCategoria>(implementacionCategorias);
		}
		return listImplementacionCategorias;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 30/07/2013
	 * @param listImplementacionCategorias the listImplementacionCategorias to set
	 */
	public void setListImplementacionCategorias(
			List<ImplementacionCategoria> listImplementacionCategorias) {
		this.listImplementacionCategorias = listImplementacionCategorias;
	}

}
