package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable{

	private String codigoPersona;
	private String nombre;
	private String apellido;
	private String nombreCompleto;
	private Date fechaNacimiento;
	private String sexo;
	private String emailPersona;
	private String pais;
	private String lenguaje;
	private String ubicacion;
	private String urlImagenPerfil;
	private String idProveedor;
	private Date fechaRegistro;
	private Date fechaModificacion;
	private String clave;
	private Set proyectoPersonas = new HashSet(0);
	private Set evaluacions = new HashSet(0);
	private Set proyectos = new HashSet(0);

	public Persona() {
	}
	
	public Persona(String codigoPersona) {
		this.codigoPersona = codigoPersona;
	}

	public Persona(String codigoPersona, String nombre, String emailPersona,
			Date fechaRegistro, Date fechaModificacion, String clave) {
		this.codigoPersona = codigoPersona;
		this.nombre = nombre;
		this.emailPersona = emailPersona;
		this.fechaRegistro = fechaRegistro;
		this.fechaModificacion = fechaModificacion;
		this.clave = clave;
	}

	public Persona(String codigoPersona, String nombre, String apellido,
			String nombreCompleto, Date fechaNacimiento, String sexo,
			String emailPersona, String pais, String lenguaje,
			String ubicacion, String urlImagenPerfil, String idProveedor,
			Date fechaRegistro, Date fechaModificacion, String clave,
			Set proyectoPersonas, Set evaluacions, Set proyectos) {
		this.codigoPersona = codigoPersona;
		this.nombre = nombre;
		this.apellido = apellido;
		this.nombreCompleto = nombreCompleto;
		this.fechaNacimiento = fechaNacimiento;
		this.sexo = sexo;
		this.emailPersona = emailPersona;
		this.pais = pais;
		this.lenguaje = lenguaje;
		this.ubicacion = ubicacion;
		this.urlImagenPerfil = urlImagenPerfil;
		this.idProveedor = idProveedor;
		this.fechaRegistro = fechaRegistro;
		this.fechaModificacion = fechaModificacion;
		this.clave = clave;
		this.proyectoPersonas = proyectoPersonas;
		this.evaluacions = evaluacions;
		this.proyectos = proyectos;
	}

	public String getCodigoPersona() {
		return this.codigoPersona;
	}

	public void setCodigoPersona(String codigoPersona) {
		this.codigoPersona = codigoPersona;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEmailPersona() {
		return this.emailPersona;
	}

	public void setEmailPersona(String emailPersona) {
		this.emailPersona = emailPersona;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getLenguaje() {
		return this.lenguaje;
	}

	public void setLenguaje(String lenguaje) {
		this.lenguaje = lenguaje;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getUrlImagenPerfil() {
		return this.urlImagenPerfil;
	}

	public void setUrlImagenPerfil(String urlImagenPerfil) {
		this.urlImagenPerfil = urlImagenPerfil;
	}

	public String getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(String idProveedor) {
		this.idProveedor = idProveedor;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public Set getProyectoPersonas() {
		return this.proyectoPersonas;
	}

	public void setProyectoPersonas(Set proyectoPersonas) {
		this.proyectoPersonas = proyectoPersonas;
	}

	public Set getEvaluacions() {
		return this.evaluacions;
	}

	public void setEvaluacions(Set evaluacions) {
		this.evaluacions = evaluacions;
	}

	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

}
