package org.memsoa.app.model;

// Generated 8/07/2013 08:12:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProyectoPersona generated by hbm2java
 */
public class ProyectoPersona implements java.io.Serializable {

	private ProyectoPersonaId id;
	private String nombrePersona;
	private String nombreRol;
	private String nombreProyecto;
	private String estadoProyecto;
	public ProyectoPersona() {
	}

	public ProyectoPersona(ProyectoPersonaId id) {
		this.id=id;
	}
	
	public ProyectoPersona(ProyectoPersonaId id, Persona persona,
			Proyecto proyecto, Rol rol) {
		this.id = id;
	}

	
	public ProyectoPersonaId getId() {
		return this.id;
	}

	public void setId(ProyectoPersonaId id) {
		this.id = id;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 18/07/2013
	 * @return the nombrePersona
	 */
	public String getNombrePersona() {
		return nombrePersona;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 18/07/2013
	 * @param nombrePersona the nombrePersona to set
	 */
	public void setNombrePersona(String nombrePersona) {
		this.nombrePersona = nombrePersona;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 18/07/2013
	 * @return the nombreRol
	 */
	public String getNombreRol() {
		return nombreRol;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 18/07/2013
	 * @param nombreRol the nombreRol to set
	 */
	public void setNombreRol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 18/07/2013
	 * @return the nombreProyecto
	 */
	public String getNombreProyecto() {
		return nombreProyecto;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 18/07/2013
	 * @param nombreProyecto the nombreProyecto to set
	 */
	public void setNombreProyecto(String nombreProyecto) {
		this.nombreProyecto = nombreProyecto;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 18/07/2013
	 * @return the estadoProyecto
	 */
	public String getEstadoProyecto() {
		return estadoProyecto;
	}

	/**
	 * @author <a href="mailto:cristian.arboleda@premize.com">Cristian M. Arboleda</a>
	 * @date 18/07/2013
	 * @param estadoProyecto the estadoProyecto to set
	 */
	public void setEstadoProyecto(String estadoProyecto) {
		this.estadoProyecto = estadoProyecto;
	}


}
